//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineHouseRentManagementSystem.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBuserSignupLoginEntities : DbContext
    {
        public DBuserSignupLoginEntities()
            : base("name=DBuserSignupLoginEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TBLAdminInfo> TBLAdminInfoes { get; set; }
        public virtual DbSet<TBLSellerInfo> TBLSellerInfoes { get; set; }
        public virtual DbSet<TBLUserInfo> TBLUserInfoes { get; set; }
        public virtual DbSet<BookingDetail> BookingDetailes { get; set; }
        public object BookingDetail { get; internal set; }
        
    }
}
