//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineHouseRentManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class HouseDetail
    {
        public int IdUs { get; set; }
        [Required(ErrorMessage = "Name is required")]
        public string Name { get; set; }
        [Required(ErrorMessage = "Email is required")]
        public string Email { get; set; }
        [Required(ErrorMessage = "ContactNumber is required")]
        public string ContactNumber { get; set; }
        [Required(ErrorMessage = "Location is required")]
        public string Location { get; set; }
        [Required(ErrorMessage = "Bedrooms is required")]
        public string Bedrooms { get; set; }
        [Required(ErrorMessage = "HouseRent is required")]
        public string HouseRent { get; set; }
        [Required(ErrorMessage = "Description is required")]
        public string Description { get; set; }

        public int Status { get; set; }
    }
}
